//json inmuebles

var inmueleslist={
    "inmuebles":[
        {
            "calle":"",
            "precio":"",
            "barrio":"",
            "ciudad":"", 
            "m2":"", 
            "habitaciones":"", 
            "baño":"", 
            "estados":"", 
            "piso":"", 
            "acensor":"", 
            "descripcion":"",
        },{
            "calle":"",
            "precio":"",
            "barrio":"",
            "ciudad":"", 
            "m2":"", 
            "habitaciones":"", 
            "baño":"", 
            "estados":"", 
            "piso":"", 
            "acensor":"", 
            "descripcion":"",
        },{
            "calle":"",
            "precio":"",
            "barrio":"",
            "ciudad":"", 
            "m2":"", 
            "habitaciones":"", 
            "baño":"", 
            "estados":"", 
            "piso":"", 
            "acensor":"", 
            "descripcion":"",
        }
    ]
};