//json inmuebles

var inmueleslist={
    "inmuebles":[
        {
            "calle":"l'Arc de Sant Ramon del Call",
            "tipo":"Local",
            "vivienda":"Alquiler",
            "precio":"4500",
            "barrio":"Gótico",
            "ciudad":"Barcelona", 
            "m2":"140", 
            "habitaciones":"diáfano", 
            "baño":"1", 
            "estado":"buen estado", 
            "piso":"Baja", 
            "acensor":"No", 
            "descripcion":"Este local situado en el barrio judío de Barcelona esta situado en una calle muy tranquila del centro de la ciudad con una dimensión de 140 metros cuadrados con unas paredes que pertenencia a una antigua muralla de la ciudad que esta protegido por el ayuntamiento de Barcelona. Local diáfano con pequeñas grutas naturales formadas por la muralla que rodea el local que pueden ser utilizadas como almacenes. Contacta con nosotros sin compromiso si deseas mas información sombre este local. Puedes llamarnos al 617. 70. 56.20.",
        },{
            "calle":"Plaza Sant Cristòfol",
            "tipo":"Piso",
            "vivienda":"Venta",
            "precio":"165000",
            "barrio":"Zona Franca",
            "ciudad":"Barcelona", 
            "m2":"90", 
            "habitaciones":"3", 
            "baño":"1", 
            "estado":"Buen Estado", 
            "piso":"2", 
            "acensor":"si", 
            "descripcion":"Vivienda  situada en  la misma Plaça Sant Cristófol.  Zona de  edificios  de nueva construcción en 1999,  esta vivienda solo tiene 15 años, amplia entrada del vestíbulo con dos escaleras, derecha e izquierda,  con ascensor en cada una de ellas y con 4 viviendas por rellano,   2 viviendas con vistas a la Plaza y 2 viviendas vistas a la Calle Energía, todas las habitaciones son exteriores ya sea a la plaza o la parte posterior con un amplio patio, lo que permite una estupenda iluminación natural. Puerta blindada, con cocina de origen  muy bien conservada, con patio / trastero donde se ubica la caldera de la calefacción y agua caliente de la vivienda, un pasillo central divide las habitaciones, dos habitaciones hacia la izquierda y el dormitorio principal y el comedor a la derecha, tanto el salón - comedor como la habitación principal tiene  un gran ventanal con acceso a la terraza con vistas a la plaza Sant Cristofol,  al fondo del pasillo, nos encontramos un baño completo con bañera. Vivienda situada en  la plaza, por lo que esta zona goza de una gran tranquilidad, lejos del ruido exterior, excelente comunicación, tanto de transportes públicos, como de carreteras, cerca de equipamientos como centros de enseñanza primaria y secundaria,  y zona comercial, como Gran Vía 2.",
        },{
            "calle":"Grífols",
            "tipo":"Piso",
            "vivienda":"Alquiler",
            "precio":"139000",
            "barrio":"Horta",
            "ciudad":"Barcelona", 
            "m2":"76", 
            "habitaciones":"4", 
            "baño":"1", 
            "estado":"Buen estado", 
            "piso":"1", 
            "acensor":"si", 
            "descripcion":"Este piso de 76 m2 distribuidos en 4 habitaciones, una de ellas al exterior doble situada junto al comedor, se convierten en zonas muy iluminadas con luz natural. Las otras 3 habitaciones , cocina y baños con ventanas al patio interior grande. Tanto el baño como la cocina han sido reformados. El edificio tiene un ascensor  y el edificio contra de 4 viviendas por rellano. Piso ubicado en una zona tranquila de Horta. Situado muy cerca de zona comercial y de colegios. Piso en buen estado y listo para entrar a vivir.",
        },{
            "calle":"Rivero",
            "tipo":"Local",
            "vivienda":"Venta",
            "precio":"295000",
            "barrio":"Horta",
            "ciudad":"Barelona", 
            "m2":"320", 
            "habitaciones":"Diáfana", 
            "baño":"1", 
            "estado":"Buen Estado", 
            "piso":"Baja", 
            "acensor":"No", 
            "descripcion":"Se vende local de amplias dimensiones. Consta de más de 300 metros cuadrados, ideal para varios tipos de negocios, como locales de ocio infantil, concesionarios, talleres, oficinas y/o distribuidoras de empresas online, entre otros. Instalación electrica equipada con doble salida, una normal y otra de fuerza que la hacen ideal para la instalación de maquinaria industrial. Consta de dos zonas de despacho, zona de recibimiento, dos aseos y entrada propia de garaje para vehículos. Llámanos sin compromiso y concierta una cita.",
        },{
            "calle":"Isop",
            "tipo":"Piso",
            "vivienda":"Venta",
            "precio":"165000",
            "barrio":"La Teixonera",
            "ciudad":"Barcelona", 
            "m2":"85", 
            "habitaciones":"1", 
            "baño":"1", 
            "estado":"Buena Estado", 
            "piso":"Ático", 
            "acensor":"si", 
            "descripcion":"Ático de 85 m2 construidos, 82 m2 útiles de los cuales 36 m2 de terraza y 46 m2 de piso cubierto, distribuidos en 1 dormitorio, baño, comedor, salón y cocina totalmente nueva. Es totalmente exterior y muy luminoso. Está totalmente reformado y la carpintería de aluminio es Climalit. Dispone de calefacción mediante radiadores de gas y 1 aire acondicionado con bomba de calor. Las instalaciones son de nueva instalación. Desde la terraza podrá disfrutar de unas maravillosas vistas a la montaña del Tibidabo y del Sol en compañía de su familia y amigos. La plaza Isop se ha reformado completamente hace pocos meses. Situado en una zona muy bien comunicada con el metro de la línea L5, parada El Coll/La Taxonera, y varias líneas de autobuses. No está muy lejos de la línea L5, parada Vall d’Hebron.",
        },{
            "calle":"Gran Via de les Corts Catalanes",
            "tipo":"Oficina",
            "vivienda":"Venta",
            "precio":"550000",
            "barrio":"Eixample Dreta",
            "ciudad":"Barelona", 
            "m2":"175", 
            "habitaciones":"4", 
            "baño":"2", 
            "estado":"Buen Estado", 
            "piso":"1", 
            "acensor":"si", 
            "descripcion":"Vivienda de una única planta de 175 m2 sin reformar pero en buen estado, distribuidos en un total de 6 estancias  las cuales se puedes amoldar a los gustos y preferencias de cada persona según su estilo y necesidad de espacio. 2 de esas estancias tienes un pequeño balcón a la calle principal y por el otro lado da acceso a un terraza privada y a modo interior tenemos acceso a un patio interior sin tapar dando cierta corriente de brisa para ventilas todas y cada una de las estancias. Es la mayoría de la vivienda hay parque, exceptuando el comedor en el que se puede ver que tipo de suelo modernista hay en él y jugando con complejas molduras del comedor que le da un carácter propio a la vivienda. Se han incorporado 4 apartados de aire acondicionado en diferentes puntos de la vivienda para poder cubrir todas las necesidades de la vivienda. La comunidad dispone de un servicio de portería. Respecto a la localización, el inmueblre se encuentra situado en el Ensanche derecho, entre las calles Bailen y la calle Girona, justo al lado de la plaza Tetuán y a 5 minutos del Arco de triunfo. Ubicado en una posición estratégica, rodeado de zona comercial, sedes bancarias de las principales entidades, y buena oferta gastronómica. Muy bien comunicado con transporte publico como metro y autobuses.",
        },{
            "calle":"Anna Piferrer",
            "tipo":"Piso",
            "vivienda":"Venta",
            "precio":"161500",
            "barrio":"Vallcarca i Penitents",
            "ciudad":"Barcelona", 
            "m2":"90", 
            "habitaciones":"3", 
            "baño":"1", 
            "estado":"Buen Estado", 
            "piso":"2", 
            "acensor":"No", 
            "descripcion":"Piso en buen estado con un recibidor de bienvenida y un corto pasillo con acceso al comedor, a la cocina y a un distribuidor para un total de 3 habitaciones dobles con armarios a medida hasta el techo muy completos y todas ellas exteriores con amplias ventanas que proporcionan muy buena luz natural a la estancia y un baño con bañera, bidet, váter y doble pica para él y para ella grande. Con opción a poner un ascensor en la finca. Situado entre el barrio de Gracia y Horta cercano a la Ronda de D'alt y a pocos metros de transporte publico, tanto metro como diferentes lineas de autobús. Infórmate sin compromiso",
        },{
            "calle":"Passatge Capdevila",
            "tipo":"Parking",
            "vivienda":"Alquiler",
            "precio":"70",
            "barrio":"Horta",
            "ciudad":"Barcelona", 
            "m2":"9", 
            "habitaciones":"-", 
            "baño":"-", 
            "estado":"-", 
            "piso":"-", 
            "acensor":"-", 
            "descripcion":"Piso en buen estado con un recibidor de bienvenida y un corto pasillo con acceso al comedor, a la cocina y a un distribuidor para un total de 3 habitaciones dobles con armarios a medida hasta el techo muy completos y todas ellas exteriores con amplias ventanas que proporcionan muy buena luz natural a la estancia y un baño con bañera, bidet, váter y doble pica para él y para ella grande. Con opción a poner un ascensor en la finca. Situado entre el barrio de Gracia y Horta cercano a la Ronda de D'alt y a pocos metros de transporte publico, tanto metro como diferentes lineas de autobús. Infórmate sin compromiso",
        },{
            "calle":"Baixada de la Plana",
            "tipo":"Local",
            "vivienda":"Alquiler",
            "precio":"1000 + Traspaso",
            "barrio":"Horta",
            "ciudad":"Barcelona", 
            "m2":"100", 
            "habitaciones":"Diáfana", 
            "baño":"2", 
            "estado":"Buen estado", 
            "piso":"Baja", 
            "acensor":"No", 
            "descripcion":"Local en traspaso diáfano con una zona de barra y otra con mesas de cafetería, con un total de 100 m2 con una capacidad para 40 comensales distribuido en mesas y pequeños soca para relajarse. El local tiene un único acceso con una entrada privada dándole doble seguridad con la doble puerta dejando una zona para un escaparate de uso propio para publicidad privada de los servicios proporcionados. Cerca de la entradas se encuentra el acceso a la zona de almacenaje y con una barra de servicio rápido. En el interior del local ai un amplio espacio para mesas y sillones con un baño para hombres y otro para mujeres. Esta incluido  todo el mobiliario que se ve en las fotografías tales como mesas, sillas, enceras y todo el material y equipamiento de la cocina. Tiene la licencia tipo C-1.",
        },{
            "calle":"Sancho Ávila",
            "tipo":"Local",
            "vivienda":"Alquiler",
            "precio":"1334",
            "barrio":"El Parc i Llacuna del Poblenou",
            "ciudad":"Barcelona", 
            "m2":"", 
            "habitaciones":"", 
            "baño":"2", 
            "estado":"Buen Estado", 
            "piso":"1", 
            "acensor":"No", 
            "descripcion":"Local en alquiler calle Sancho Ávila de Barcelona. Zona de 22@. Local situado en un edificio destinado en su totalidad a empresas. Dispone de servicio de conserje, consumos, limpieza, comunidad, etc. dichos gastos se incluyen en el recibo del alquiler valorados en 555€/mes. Entresuelo de superficie 800m2, en una sola planta, la parte anterior del edificio de unos 200m2 está actualmente dividida en varios despachos, y la parte interior en un solo local de unos 600m2, dispone de zona de lavabos para señoras y caballeros. En algunas zonas existe una altura máxima de 2metros, debido a unas jácenas, de la estructura del edificio, por lo que limita las posibilidades comerciales. Se encuentra ubicada en una zona privilegiada de Barcelona, denominada Zona del 22@. Muy cerca de la Torre Agbar del Jean Nouvel y Torre de oficinas de David Chipperfield. Donde el Ayuntamiento ha delimitado las actividades que se pueden desarrollarse, por ello tienen unas limitaciones concretas en las actividades a ejercer, debido al proyecto 22@. Estas actividades que el ayuntamiento de Barcelona quiere potenciar en la zona tienen que ser actividades de carácter externo, es decir todas aquellas dirigidas a la cultura, tecnología, etc. o de carácter interno, comotodas aquellas como oficinas o almacén, etc.",
        }
    ]
};